#!/bin/sh

script_dir="$(realpath "$(dirname "$0")")"
packages_filename="$(realpath "$script_dir/../.packages")"

update_packages() {
  sudo apt update && sudo apt upgrade
}

install_packages() {
  # shellcheck disable=SC2046
  sudo apt install -y $(cat "$packages_filename")
}

update_packages &&
  install_packages